Tla2528
libhal/libhal-expander pull request #5
Opened 2024-11-26 21:30 UTC by MichaelYKersey

The tla2528 is an i2c-based GPIO expander and ADC mux. It has 8 pins that can each be independently configured and operated as GPIO or ADC. This is a port of the tla2528 driver and adapters from the [SJSU robotics team](https://github.com/SJSURoboticsTeam/urc-control-systems-2024/pull/12). 

Features
- ADC readings
- Digital input readings (bus & individual)
- Digital output writing (bus & individual) (push-pull & open-drain)
- Adapters for each

Missing/future/unimplemented features:
- TLA reset on object creation
- ADC 16-bit precision (currently 12-bit, but chip allows for more)
- ADC channel verification (redundancy)

2024-11-26 21:56 UTC, MichaelYKersey commented
currently, the reset command is declared as a private method but is unimplemented. Should it be removed? or is it better to leave it there for the binary interface consistency (I'm not sure how ABIs work)

2024-11-27 14:21 UTC, kammce requested changes
Great work! Much of my comments have to do with formatting and documentation. The rest mostly looks good.

2024-11-27 14:21 UTC, kammce commented on demos/applications/tla2528_analog_input.cpp
> +#include <resource_list.hpp>
```suggestion
#include <array>

#include <libhal-util/bit.hpp>
#include <libhal-util/i2c.hpp>
#include <libhal-util/serial.hpp>
#include <libhal-util/steady_clock.hpp>
#include <libhal/input_pin.hpp>
#include <libhal/units.hpp>
#include <libhal-expander/tla2528.hpp>
#include <libhal-expander/tla2528_adapters.hpp>

#include <resource_list.hpp>
```

Suggestion made based on https://libhal.github.io/4.1/contributor_guide/style/#s143-include-order.

2024-11-27 14:21 UTC, kammce commented on demos/applications/tla2528_analog_input.cpp
> +}
All files should end with a newline. I'm adding a patch to have CI check demos directory files as well.

2024-11-27 14:21 UTC, kammce commented on demos/applications/tla2528_input_pin.cpp
> +
```suggestion
#include <array>

#include <libhal-util/bit.hpp>
#include <libhal-util/i2c.hpp>
#include <libhal-util/serial.hpp>
#include <libhal-util/steady_clock.hpp>
#include <libhal/input_pin.hpp>
#include <libhal/units.hpp>
#include <libhal-expander/tla2528.hpp>
#include <libhal-expander/tla2528_adapters.hpp>

#include <resource_list.hpp>

```

2024-11-27 14:21 UTC, kammce commented on include/libhal-expander/tla2528_adapters.hpp
> + */
```suggestion
/**
 * @brief create a hal::input_pin driver using the tla2528 driver
 *
 * @param p_channel pin acting as an input pin
 * @param p_settings input pin settings, default is no resistor
 * @throws hal::argument_out_of_domain - if p_channel out of range (>7)
 * @throws hal::resource_unavailable_try_again - if an adapter has already been
 * been made for the pin
 * @throws hal::no_such_device - no device responded on i2c bus
 */
```

I find the spacing harder to read than keeping everything together. Can you make this change to other comments like this as well.

2024-11-27 14:21 UTC, kammce commented on include/libhal-expander/tla2528_adapters.hpp
> +                                 hal::input_pin::settings const& p_settings);
```suggestion
                                 hal::input_pin::settings const& p_settings = {.resistor = none});
```

May be a nice QOL feature to have this have a default settings parameter vs having the user have to supply each.

2024-11-27 14:21 UTC, kammce commented on src/tla2528.cpp
> +  // TODO: reset command
```suggestion
  // TODO(#issue-number): Add reset command
```

Each commented TODO should also have an issue and issue number accompanied with it so its easier to follow the technical debt. Please create an issue and label it with technical debt. If you cannot label it due to permission reasons, say so in a reply and I'll label the issue for you.

2024-11-27 14:21 UTC, kammce commented on include/libhal-expander/tla2528.hpp
> + * digital input, and digital out over i2c. The i2c address is configured by
```suggestion
 * input pin, and digital pin over i2c. The i2c address is configured by
```

Might as well use the same terminology we use for the interfaces.

2024-11-27 14:21 UTC, kammce commented on include/libhal-expander/tla2528.hpp
> +   */
```suggestion
  /**
   * @brief set digital output level pin
   *
   * The device will write to a register that caches the desired output state.
   * When a pin is in a digital output mode it will reference the desired state
   * cache. If the pin is not set to digital output it will just be stored.
   *
   * @param p_channel pin to set output
   * @param p_high the output level of the pin, true is high, false is low.
   * @throws hal::argument_out_of_domain - if p_channel out of range (>7)
   * @throws hal::no_such_device - no device responded on i2c bus
   */
```

Put the description after the brief then define the parameters and throwables. But I also don't think the description makes sense to a reader. I think the underlying implementation, in this case, isn't important enough to spell out to the API user. In other cases I could see a rationale for stating the implementation details in order to warn a user about a potentially expensive operation. But in this case, I don't see it as very useful.

2024-11-27 14:21 UTC, kammce commented on include/libhal-expander/tla2528.hpp
> +   * @throws hal::no_such_device - no device responded on i2c bus
```suggestion
```

I think its fine to only list the exceptions that this driver explicity emits vs what the underlying drivers use. Yes, an i2c driver emits a "no such device" exception at every call that interacts with i2c, but tracking all of these exception through comments is tedious and error prone. We are working on tools to make this easier. The developer using this driver should also implicitly know that i2c exceptions can be emitted from a driver that use i2c. So we can remove all of these throws statements for i2c specific things.

2024-11-27 14:21 UTC, kammce commented on include/libhal-expander/tla2528.hpp
> +   * @return if the pin's digital read value is high.
```suggestion
   * @return true if the pin's digital read value is high.
```

2024-11-27 14:21 UTC, kammce commented on include/libhal-expander/tla2528.hpp
> +   * correlate with the true value.
It would be nice to put this in the returns block vs in the description so its clear when the reader reads the return documentation.

2024-11-27 14:21 UTC, kammce commented on include/libhal-expander/tla2528.hpp
> +   * correlate with the true value.
Same goes for the others.

2024-11-27 14:21 UTC, kammce commented on src/tla2528.cpp
> +  };
```suggestion
  constexpr std::array<hal::byte, 2> read_cmd_buffer = {
    op_codes::continuous_register_read, register_addresses::pin_cfg
  };
```

Should be able to make arrays like these that do not change into constexpr objects.

2024-11-27 14:21 UTC, kammce commented on src/tla2528.cpp
> +          hal::bit_extract(channel_mask, gpio_cfg_reg))) {
```suggestion
    if (hal::bit_extract(channel_mask, m_object_created) &&
        !(hal::bit_extract(channel_mask, pin_cfg_reg) ||
          hal::bit_extract(channel_mask, gpio_cfg_reg))) {
```

This logic is hard to follow. The `m_object_created` makes sense, that this is checking if the adaptor has been created but the other flags are not obvious. What you can do is break these up into bools that represent what you mean to express here. Something like

```C++
bool object_already_created = hal::bit_extract(channel_mask, m_object_created);
// etc for what the other ones mean.
bool misconfigured = not hal::bit_extract(channel_mask, pin_cfg_reg) || hal::bit_extract(channel_mask, gpio_cfg_reg);
if (object_already_created && misconfigured) { /* ... */ }
```

Something like that.

2024-11-27 14:21 UTC, kammce commented on src/tla2528.cpp
> +                                          m_gpo_value };
```suggestion
  constexpr std::array<hal::byte, 3> cmd_buffer = { op_codes::single_register_write,
                                          register_addresses::gpo_value,
                                          m_gpo_value };
```

2024-11-27 14:21 UTC, kammce commented on src/tla2528.cpp
> +  // TODO: look into averaging & channel validation
```suggestion
  // TODO(#issue): look into averaging & channel validation
```

Make an issue for this.

2024-11-27 14:21 UTC, kammce commented on src/tla2528_adapters.cpp
> +  }
You use this same logic a few times in the adaptors. Would make sense to make a helper function for this.

2024-11-27 14:21 UTC, kammce commented on src/tla2528.cpp
> +  // TODO: reset command
```suggestion
  // TODO(#issue-number): reset command
```

Make an technical debt issue for this. Also you might as well call reset() here and define it with the TODO. That way the code is already in place and the empty function has the todo embedded in it.

2024-11-27 14:21 UTC, kammce commented on demos/applications/tla2528_output_pin.cpp
> +    0;  // output counts in binary to go though all out put combinations
```suggestion
  // output counts in binary to go though all out put combinations
  hal::byte counter = 0;  
```

The newline 0 looks really odd. You can put the comment one line above.

2024-11-27 14:21 UTC, kammce commented on demos/applications/tla2528_input_pin.cpp
> +
Do this everywhere else as well.

2024-11-27 14:21 UTC, kammce commented on src/tla2528_adapters.cpp
> +    .set(hal::bit_mask::from(m_channel));
```suggestion
    .clear(hal::bit_mask::from(m_channel));
```
Shouldn't this be clear?

2024-11-27 14:21 UTC, kammce commented on src/tla2528_adapters.cpp
> +    .set(hal::bit_mask::from(m_channel));
Do the same for the others.

2024-11-27 14:22 UTC, kammce commented
> currently, the reset command is declared as a private method but is unimplemented. Should it be removed? or is it better to leave it there for the binary interface consistency (I'm not sure how ABIs work)

See my comment on what you should do about reset. As for ABI, class functions do not effect the ABI of a function so nothing to worry about from that angle.

2025-01-04 05:12 UTC, MichaelYKersey commented on src/tla2528.cpp
> +  // TODO: reset command
I made the issue(s), I don't have permission to label them.

2025-01-04 05:57 UTC, MichaelYKersey commented on include/libhal-expander/tla2528.hpp
> + * digital input, and digital out over i2c. The i2c address is configured by
Which interface are you referring to?

2025-01-04 07:05 UTC, MichaelYKersey commented on src/tla2528.cpp
> +          hal::bit_extract(channel_mask, gpio_cfg_reg))) {
Tried to do what you suggested, look it over.

2025-01-04 07:05 UTC, MichaelYKersey commented on include/libhal-expander/tla2528.hpp
> +   */
Should I remove the descriptions, improve the clarity, or was it just unnecessary work that can be left alone?

Either way, I changed the order as requested.

2025-01-04 13:34 UTC, kammce commented on include/libhal-expander/tla2528.hpp
> + * digital input, and digital out over i2c. The i2c address is configured by
`hal::input_pin` and `hal::output_pin` so you can use the terms input pin and output pin which assume they are digital.

2025-01-04 13:36 UTC, kammce commented on include/libhal-expander/tla2528.hpp
> +   */
Reading it over again, you can probably eliminate that section. If anything may be useful to be as a comment in the source file for readers looking to understand the code. I'll leave it to you if you want to place this somewhere in the source.

2025-01-08 13:13 UTC, kammce commented
I can perform a other review once CI has passed. I recently re-enabled clang-tidy static analysis which is why there are so many new errors popping up.

2025-01-11 20:08 UTC, MichaelYKersey commented on src/tla2528.cpp
> +          hal::bit_extract(channel_mask, gpio_cfg_reg))) {
approved in-person

2025-01-11 20:19 UTC, MichaelYKersey commented on include/libhal-expander/tla2528.hpp
> + * digital input, and digital out over i2c. The i2c address is configured by
Updated, look over it over

2025-01-11 20:44 UTC, kammce approved these changes
Looks good! One last little fix in the form of a C style cast and we can submit this.

2025-01-11 20:44 UTC, kammce commented on src/tla2528.cpp
> +  return (float)data / (float)4095.0;
Use C++ style casts (clang-tidy should have caught this). 
```suggestion
  return static_cast<float>(data) / 4095.0f;
```

2025-01-12 00:16 UTC, MichaelYKersey commented on include/libhal-expander/tla2528.hpp
> + * digital input, and digital out over i2c. The i2c address is configured by
marking as resolved based on general comment
"Looks good! One last little fix in the form of a C style cast and we can submit this."

2025-01-12 01:56 UTC, merged